export interface StoreProducts {
  name: string;
  category: string;
  subcategory: string;
}
export const storeProducts: StoreProducts[] = [
  { name: 'Pork', category: 'Food', subcategory: 'Meat' },
  { name: 'Beef', category: 'Food', subcategory: 'Meat' },
  { name: 'Turkey', category: 'Food', subcategory: 'Meat' },
  { name: 'Duck', category: 'Food', subcategory: 'Meat' },
  { name: 'Venison', category: 'Food', subcategory: 'Meat' },
  { name: 'Pepper', category: 'Food', subcategory: 'Vegetables' },
  { name: 'Broccoli', category: 'Food', subcategory: 'Vegetables' },
  { name: 'Zucchini', category: 'Food', subcategory: 'Vegetables' },
  { name: 'Eggplant', category: 'Food', subcategory: 'Vegetables' },
  { name: 'Apple', category: 'Food', subcategory: 'Fruits' },
  { name: 'Banana', category: 'Food', subcategory: 'Fruits' },
  { name: 'Orange', category: 'Food', subcategory: 'Fruits' },
  { name: 'Grapes', category: 'Food', subcategory: 'Fruits' },
  { name: 'Mango', category: 'Food', subcategory: 'Fruits' },
  { name: 'Milk', category: 'Food', subcategory: 'Dairy' },
  { name: 'Cheese', category: 'Food', subcategory: 'Dairy' },
  { name: 'Yogurt', category: 'Food', subcategory: 'Dairy' },
  { name: 'Butter', category: 'Food', subcategory: 'Dairy' },
  { name: 'Eggs', category: 'Food', subcategory: 'Dairy' },
  { name: 'Bread', category: 'Food', subcategory: 'Bakery' },
  { name: 'Bagels', category: 'Food', subcategory: 'Bakery' },
  { name: 'Croissants', category: 'Food', subcategory: 'Bakery' },
  { name: 'Muffins', category: 'Food', subcategory: 'Bakery' },
  { name: 'Cakes', category: 'Food', subcategory: 'Bakery' },
  { name: 'Soup', category: 'Food', subcategory: 'Canned Foods' },
  { name: 'Tomatoes', category: 'Food', subcategory: 'Canned Foods' },
  { name: 'Beans', category: 'Food', subcategory: 'Canned Foods' },
  { name: 'Tuna', category: 'Food', subcategory: 'Canned Foods' },
  { name: 'Vegetables', category: 'Food', subcategory: 'Canned Foods' },
  { name: 'Cola', category: 'Beverages', subcategory: 'Soft Drinks' },
  { name: 'Lemonade', category: 'Beverages', subcategory: 'Soft Drinks' },
  { name: 'Ginger Ale', category: 'Beverages', subcategory: 'Soft Drinks' },
  { name: 'Root Beer', category: 'Beverages', subcategory: 'Soft Drinks' },
  { name: 'Apple Juice', category: 'Beverages', subcategory: 'Juices' },
  { name: 'Orange Juice', category: 'Beverages', subcategory: 'Juices' },
  { name: 'Grapefruit Juice', category: 'Beverages', subcategory: 'Juices' },
  { name: 'Pineapple Juice', category: 'Beverages', subcategory: 'Juices' },
  { name: 'Cranberry Juice', category: 'Beverages', subcategory: 'Juices' },
  { name: 'Coffee Beans', category: 'Beverages', subcategory: 'Coffee & Tea' },
  { name: 'Green Tea', category: 'Beverages', subcategory: 'Coffee & Tea' },
  { name: 'Black Tea', category: 'Beverages', subcategory: 'Coffee & Tea' },
  { name: 'Herbal Tea', category: 'Beverages', subcategory: 'Coffee & Tea' },
  {
    name: 'Instant Coffee',
    category: 'Beverages',
    subcategory: 'Coffee & Tea',
  },
  { name: 'Beer', category: 'Beverages', subcategory: 'Alcoholic Drinks' },
  { name: 'Wine', category: 'Beverages', subcategory: 'Alcoholic Drinks' },
  { name: 'Whiskey', category: 'Beverages', subcategory: 'Alcoholic Drinks' },
  { name: 'Vodka', category: 'Beverages', subcategory: 'Alcoholic Drinks' },
  { name: 'Rum', category: 'Beverages', subcategory: 'Alcoholic Drinks' },
  {
    name: 'All-Purpose Cleaner',
    category: 'Household Items',
    subcategory: 'Cleaning Supplies',
  },
  {
    name: 'Dish Soap',
    category: 'Household Items',
    subcategory: 'Cleaning Supplies',
  },
  {
    name: 'Laundry Detergent',
    category: 'Household Items',
    subcategory: 'Cleaning Supplies',
  },
  {
    name: 'Broom',
    category: 'Household Items',
    subcategory: 'Cleaning Supplies',
  },
  {
    name: 'Mop',
    category: 'Household Items',
    subcategory: 'Cleaning Supplies',
  },
  {
    name: 'Shampoo',
    category: 'Household Items',
    subcategory: 'Personal Care',
  },
  { name: 'Soap', category: 'Household Items', subcategory: 'Personal Care' },
  {
    name: 'Toothpaste',
    category: 'Household Items',
    subcategory: 'Personal Care',
  },
  {
    name: 'Deodorant',
    category: 'Household Items',
    subcategory: 'Personal Care',
  },
  {
    name: 'Toilet Paper',
    category: 'Household Items',
    subcategory: 'Personal Care',
  },
  {
    name: 'Pots and Pans',
    category: 'Household Items',
    subcategory: 'Kitchenware',
  },
  { name: 'Utensils', category: 'Household Items', subcategory: 'Kitchenware' },
  {
    name: 'Plates and Bowls',
    category: 'Household Items',
    subcategory: 'Kitchenware',
  },
  { name: 'Cutlery', category: 'Household Items', subcategory: 'Kitchenware' },
  {
    name: 'Glassware',
    category: 'Household Items',
    subcategory: 'Kitchenware',
  },
  { name: 'Smartphones', category: 'Electronics', subcategory: 'Gadgets' },
  { name: 'Smartphones', category: 'Electronics', subcategory: 'Gadgets' },
  { name: 'Tablets', category: 'Electronics', subcategory: 'Gadgets' },
  { name: 'Laptops', category: 'Electronics', subcategory: 'Gadgets' },
  { name: 'Smartwatches', category: 'Electronics', subcategory: 'Gadgets' },
  { name: 'Headphones', category: 'Electronics', subcategory: 'Gadgets' },
  { name: 'Refrigerator', category: 'Electronics', subcategory: 'Appliances' },
  { name: 'Microwave', category: 'Electronics', subcategory: 'Appliances' },
  { name: 'Blender', category: 'Electronics', subcategory: 'Appliances' },
  {
    name: 'Vacuum Cleaner',
    category: 'Electronics',
    subcategory: 'Appliances',
  },
  {
    name: 'Washing Machine',
    category: 'Electronics',
    subcategory: 'Appliances',
  },
];
